[tools]
kubectl = "latest"
node = "22"
uv = "latest"
"pipx:azure-cli" = { version = "latest", uvx_args = "--prerelease=allow" }
pnpm = "latest"
helm = "latest"
"npm:opencode-ai" = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
rust = "latest"
"cargo:erdtree" = "latest"
