monorepo_root = true

[monorepo]
config_roots = ["tools/*"]

[shell_alias]
dots = "cd {{config_root}}"

[tasks.install]
description = "Install all dotfiles tools"
depends = ["//tools/...:install"]

[tasks.check]
description = "Run all checks"
depends = ["//tools/...:check"]

[tasks.restow]
description = "Restow dotfiles into $HOME"
dir = "{{config_root}}"
run = 'stow --restow -v --target="$HOME" .'
