monorepo_root = true

[monorepo]
config_roots = ["tools/python"]

[tasks.install]
description = "Install all dotfiles tools"
depends = ["//tools/python:install"]

[tasks.check]
description = "Run all checks"
depends = ["//tools/python:check"]
