workspace-path = "~/.herdr/workspaces/{{ repo }}/{{ name | sanitize }}"

[[post-create]]
copy-envs = "wt copy-ignored"

[[post-remove]]
close-herdr = "herdr-ws close --repo '{{ repo }}' --name '{{ name }}' --path '{{ workspace_path }}'"

[copy-ignored]
exclude = [".env.compose", "*node_modules/*"]
