[ui.colors]
"selected" = { bg = "#313244" }

[preview]
revision_command = [
  "util",
  "exec",
  "--",
  "bash",
  "-c",
  "jj show --color always --git -r $change_id | delta --dark --paging=never --line-numbers --side-by-side --tabs 2",
]
oplog_command = [
  "util",
  "exec",
  "--",
  "bash",
  "-c",
  "jj op show $operation_id --git --color always | delta --dark --paging=never --line-numbers --side-by-side --tabs 2",
]
file_command = [
  "util",
  "exec",
  "--",
  "bash",
  "-c",
  "jj diff --color always --git -r $change_id $file | delta --dark --paging=never --line-numbers --side-by-side --tabs 2",
]
