[ui.colors]
"selected" = { bg = "#313244" }

[preview]
revision_command = [
  "show",
  "--color",
  "always",
  "--config",
  'ui.diff-formatter=["difft","--color=always","--graph-limit=500000","--byte-limit=500000","--width=$width","$left","$right"]',
  "-r",
  "$change_id",
]
file_command = [
  "diff",
  "--color",
  "always",
  "--config",
  'ui.diff-formatter=["difft","--color=always","--graph-limit=500000","--byte-limit=500000","--width=$width","$left","$right"]',
  "-r",
  "$change_id",
  "$file",
]
