[ui.colors]
"selected" = { bg = "#313244" }

[preview]
revision_command = [
  "util",
  "exec",
  "--",
  "env",
  "DFT_GRAPH_LIMIT=500000",
  "DFT_BYTE_LIMIT=500000",
  "difft-preview",
  "revision",
  "$change_id",
]
file_command = [
  "util",
  "exec",
  "--",
  "env",
  "DFT_GRAPH_LIMIT=500000",
  "DFT_BYTE_LIMIT=500000",
  "difft-preview",
  "file",
  "$change_id",
  "$file",
]
