promptToReturnFromSubprocess: false
gui:
  sidePanelWidth: 0.2
git:
  pagers:
    - pager: delta --dark --paging=never --line-numbers --side-by-side --tabs 2
      colorArg: always
    - externalDiffCommand: difft --color=always
