"""Generate per-workspace env files for Docker Compose and the app."""

import argparse
import os
import sys


def add_parser(subparsers: argparse._SubParsersAction) -> None:
    parser = subparsers.add_parser(
        "env",
        help="generate per-workspace env files for Docker Compose and the app",
    )
    parser.set_defaults(run=run)


def run(args: argparse.Namespace) -> int:
    names = (
        "WORKSPACE_NAME",
        "COMPOSE_NAME",
        "APP_PORT",
        "POSTGRES_PORT",
        "DB_NAME",
        "MINIO_PORT",
        "MINIO_CONSOLE_PORT",
    )
    values = {}
    for name in names:
        value = os.environ.get(name)
        if not value:
            print(f"wt env: {name} is not set", file=sys.stderr)
            return 1
        values[name] = value

    db_user = "peace_user"
    db_password = "peace_test"
    db_url = f"postgres://{db_user}:{db_password}@localhost:{values['POSTGRES_PORT']}/{values['DB_NAME']}"
    minio_url = f"http://localhost:{values['MINIO_PORT']}"

    compose_vars = [
        f"WORKSPACE_NAME={values['WORKSPACE_NAME']}",
        f"COMPOSE_PROJECT_NAME={values['COMPOSE_NAME']}",
        f"APP_PORT={values['APP_PORT']}",
        f"POSTGRES_PORT={values['POSTGRES_PORT']}",
        f"POSTGRES_DB={values['DB_NAME']}",
        f"MINIO_PORT={values['MINIO_PORT']}",
        f"MINIO_CONSOLE_PORT={values['MINIO_CONSOLE_PORT']}",
    ]
    compose_block = "# AUTO-GENERATED BY WT\n" + "\n".join(compose_vars) + "\n"
    with open(".env.compose", "w") as file:
        _ = file.write(compose_block)

    update_env_file(
        ".env.development.local",
        {"DATABASE_URL": db_url, "AWS_ENDPOINT_URL": minio_url},
    )
    return 0


def update_env_file(path: str, updates: dict[str, str]):
    lines: list[str] = []
    seen = set[str]()

    if os.path.exists(path):
        with open(path) as file:
            lines = file.read().splitlines()

        for index, line in enumerate(lines):
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if "=" in stripped:
                key = stripped.split("=", 1)[0]
                if key in updates:
                    lines[index] = f'{key}="{updates[key]}"'
                    seen.add(key)

    new_keys = [key for key in updates if key not in seen]
    if new_keys:
        if lines and lines[-1].strip():
            lines.append("")
        lines.append("# AUTO-GENERATED BY WT")
        for key in new_keys:
            lines.append(f'{key}="{updates[key]}"')

    with open(path, "w") as file:
        _ = file.write("\n".join(lines) + "\n")
