[env]
_.file = { path = "~/.env" }

[settings]
experimental = true

[tools]
node = "22"
uv = "latest"

"pipx:azure-cli" = { version = "latest", uvx_args = "--prerelease=allow" }
kubectl = "latest"
helm = "latest"

# shell
"nix:zsh" = "latest"
"oh-my-posh" = "latest"

# modern command line tools 
"bat" = "latest"
"fd" = "latest"
"eza" = "latest"
"just" = "latest"
"fzf" = "latest"
"yazi" = "latest"
"zoxide" = "latest"
"delta" = "latest"
"difftastic" = "latest"
"ripgrep" = "latest"
"nix:git-town" = "latest"
"lazygit" = "latest"
"nix:erdtree" = "latest"

# dev tools
"neovim" = "0.12.2"
"opencode" = "latest"
"github-cli" = "latest"
# nvim deps
"npm:tree-sitter-cli" = "latest"
"nix:tree-sitter" = "latest"
"npm:oxfmt" = "latest"
"pipx:basedpyright" = "latest"
"pipx:ruff" = "latest"
# nvim util deps
"nix:gnumake" = "latest"
"nix:unzip" = "latest"
"nix:xclip" = "latest"
make = "latest"
"nix:gcc" = "latest"
"pi" = "latest"
"worktrunk" = "latest"
"nix:stow" = "latest"
"aqua:joshmedeski/sesh" = "latest"
"nix:gh-dash" = "latest"
"npm:playwriter" = "latest"
