[settings]
experimental = true

[tools]
node = "22"
uv = "latest"

"pipx:azure-cli" = { version = "latest", uvx_args = "--prerelease=allow" }
kubectl = "latest"
helm = "latest"

# shell
"nix:zsh" = "latest"
"nix:oh-my-posh" = "latest"

# modern command line tools 
"nix:bat" = "latest"
"nix:fd" = "latest"
"nix:eza" = "latest"
"nix:just" = "latest"
"nix:fzf" = "latest"
"nix:yazi" = "latest"
"nix:zoxide" = "latest"
"nix:delta" = "latest"
"nix:difftastic" = "latest"
"nix:ripgrep" = "latest"
"nix:git-town" = "latest"
"nix:lazygit" = "latest"
"nix:erdtree" = "latest"

# dev tools
"nix:neovim" = "latest"
"npm:opencode-ai" = "latest"
"nix:gh" = "latest"
# nvim deps
"npm:tree-sitter-cli" = "latest"
"nix:tree-sitter" = "latest"
"npm:oxfmt" = "latest"
# nvim util deps
"nix:gnumake" = "latest"
"nix:unzip" = "latest"
"nix:xclip" = "latest"
make = "latest"
"nix:gcc" = "latest"
